# order-dbsync-infra
services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: order-dbsync-kafka
    ports:
      - "9092:9092"

    environment: #기존 Broker에서 3.x ver 이후의 Zookeeper 기반 KRaft 모드(Controller/Broker) 역할 정의 필요
      KAFKA_NODE_ID: 1 # Kafka Cluster에서 브로커를 식별하기 위한 id 값, 단일 브로커 = 1
      KAFKA_PROCESS_ROLES: broker,controller # 이 kafka가 하는 역할은 메시지를 중재하는 broker, 클러스터를 관리하는 controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093 #9092 : client 접속 9093 : controller 내부 통신
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://order-dbsync-kafka:9092 #client에게 컨테이너 통신을 위한 엔드포인트 통보 주소
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER #controller 통신에 사용할 리스너
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@order-dbsync-kafka:9093 # controller cluster 구성
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # dbsync 전용 단일 브로커 / 단일 topic

    networks:
      - order-dbsync-network


  kafka-connect:
    image: debezium/connect:2.6
    container_name: order-dbsync-kafka-connect
    ports:
      - "8083:8083"

    environment:
      BOOTSTRAP_SERVERS: order-dbsync-kafka:9092
      GROUP_ID: order-dbsync-connect-group

      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      CONNECT_REST_ADVERTISED_HOST_NAME: order-dbsync-kafka-connect

    depends_on:
      - kafka

    networks:
      - order-dbsync-network


networks:
  order-dbsync-network:
    external: true